
#TODO: make support multiple OSes
#detect os: (not that bad)
#https://stackoverflow.com/questions/714100/os-detecting-makefile
#mingw flags to not have console window
#https://stackoverflow.com/questions/4441551/how-to-stop-a-program-compiled-with-mingw-g-from-opening-a-console-window-in
build: ./src/main.c
	gcc ./src/main.c -o launcher

clean:
	rm -f ./launcher.exe