package electrosphere.net.synchronization.enums;

/**
 * List of enums of all fields and their associated ids.
 */
public class FieldIdEnums {

    public static final int TREE_CLIENTATTACKTREE_SYNCEDFIELD_STATE_ID = 0;
    public static final int TREE_CLIENTATTACKTREE_SYNCEDFIELD_DRIFTSTATE_ID = 1;
    public static final int TREE_CLIENTATTACKTREE_SYNCEDFIELD_CURRENTMOVEID_ID = 2;
    public static final int TREE_SERVERATTACKTREE_SYNCEDFIELD_STATE_ID = 3;
    public static final int TREE_SERVERATTACKTREE_SYNCEDFIELD_DRIFTSTATE_ID = 4;
    public static final int TREE_SERVERATTACKTREE_SYNCEDFIELD_CURRENTMOVEID_ID = 5;
    public static final int TREE_CLIENTBLOCKTREE_SYNCEDFIELD_STATE_ID = 6;
    public static final int TREE_CLIENTBLOCKTREE_SYNCEDFIELD_CURRENTBLOCKVARIANT_ID = 7;
    public static final int TREE_SERVERBLOCKTREE_SYNCEDFIELD_STATE_ID = 8;
    public static final int TREE_SERVERBLOCKTREE_SYNCEDFIELD_CURRENTBLOCKVARIANT_ID = 9;
    public static final int TREE_CLIENTTOOLBARSTATE_SYNCEDFIELD_SELECTEDSLOT_ID = 30;
    public static final int TREE_SERVERTOOLBARSTATE_SYNCEDFIELD_SELECTEDSLOT_ID = 31;
    public static final int TREE_CLIENTDOOR_SYNCEDFIELD_STATE_ID = 36;
    public static final int TREE_SERVERDOOR_SYNCEDFIELD_STATE_ID = 37;
    public static final int TREE_CLIENTGRAVITY_SYNCEDFIELD_STATE_ID = 16;
    public static final int TREE_SERVERGRAVITY_SYNCEDFIELD_STATE_ID = 11;
    public static final int TREE_CLIENTGROWTH_SYNCEDFIELD_STATUS_ID = 38;
    public static final int TREE_SERVERGROWTH_SYNCEDFIELD_STATUS_ID = 39;
    public static final int TREE_IDLE_SYNCEDFIELD_STATE_ID = 12;
    public static final int TREE_SERVERIDLE_SYNCEDFIELD_STATE_ID = 13;
    public static final int TREE_CLIENTCHARGESTATE_SYNCEDFIELD_CHARGES_ID = 34;
    public static final int TREE_SERVERCHARGESTATE_SYNCEDFIELD_CHARGES_ID = 35;
    public static final int TREE_CLIENTLIFETREE_SYNCEDFIELD_STATE_ID = 10;
    public static final int TREE_SERVERLIFETREE_SYNCEDFIELD_STATE_ID = 17;
    public static final int TREE_CLIENTLODTREE_SYNCEDFIELD_LODLEVEL_ID = 40;
    public static final int TREE_SERVERLODTREE_SYNCEDFIELD_LODLEVEL_ID = 41;
    public static final int TREE_CLIENTSTANCECOMPONENT_SYNCEDFIELD_STATE_ID = 28;
    public static final int TREE_SERVERSTANCECOMPONENT_SYNCEDFIELD_STATE_ID = 29;
    public static final int TREE_CLIENTEDITORMOVEMENTTREE_SYNCEDFIELD_FACING_ID = 32;
    public static final int TREE_SERVEREDITORMOVEMENTTREE_SYNCEDFIELD_FACING_ID = 33;
    public static final int TREE_CLIENTGROUNDMOVEMENTTREE_SYNCEDFIELD_FACING_ID = 14;
    public static final int TREE_SERVERGROUNDMOVEMENTTREE_SYNCEDFIELD_FACING_ID = 15;
    public static final int TREE_CLIENTJUMPTREE_SYNCEDFIELD_STATE_ID = 18;
    public static final int TREE_CLIENTJUMPTREE_SYNCEDFIELD_CURRENTFRAME_ID = 22;
    public static final int TREE_CLIENTJUMPTREE_SYNCEDFIELD_CURRENTJUMPFORCE_ID = 23;
    public static final int TREE_SERVERJUMPTREE_SYNCEDFIELD_STATE_ID = 19;
    public static final int TREE_SERVERJUMPTREE_SYNCEDFIELD_CURRENTFRAME_ID = 20;
    public static final int TREE_SERVERJUMPTREE_SYNCEDFIELD_CURRENTJUMPFORCE_ID = 21;
    public static final int TREE_CLIENTSPRINTTREE_SYNCEDFIELD_STATE_ID = 26;
    public static final int TREE_SERVERSPRINTTREE_SYNCEDFIELD_STATE_ID = 27;
    public static final int TREE_CLIENTWALKTREE_SYNCEDFIELD_STATE_ID = 24;
    public static final int TREE_SERVERWALKTREE_SYNCEDFIELD_STATE_ID = 25;

}
