/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator */

#ifndef _Included_electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator
#define _Included_electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator
#ifdef __cplusplus
extern "C" {
#endif
#undef electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator_SIMULATE_TIMESTEP
#define electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator_SIMULATE_TIMESTEP 0.1f
#undef electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator_GRAVITY_CONST
#define electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator_GRAVITY_CONST -100.0f
/*
 * Class:     electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator
 * Method:    init
 * Signature: (F)V
 */
JNIEXPORT void JNICALL Java_electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator_init
  (JNIEnv *, jclass, jfloat);

/*
 * Class:     electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator
 * Method:    simulate
 * Signature: (Ljava/util/List;F)V
 */
JNIEXPORT void JNICALL Java_electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator_simulate
  (JNIEnv *, jclass, jobject, jfloat);

/*
 * Class:     electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_electrosphere_server_physics_fluid_simulator_FluidAcceleratedSimulator_free
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
