/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class electrosphere_client_fluid_cache_FluidChunkData */

#ifndef _Included_electrosphere_client_fluid_cache_FluidChunkData
#define _Included_electrosphere_client_fluid_cache_FluidChunkData
#ifdef __cplusplus
extern "C" {
#endif
#undef electrosphere_client_fluid_cache_FluidChunkData_CHUNK_SIZE
#define electrosphere_client_fluid_cache_FluidChunkData_CHUNK_SIZE 18L
#undef electrosphere_client_fluid_cache_FluidChunkData_CHUNK_DATA_GENERATOR_SIZE
#define electrosphere_client_fluid_cache_FluidChunkData_CHUNK_DATA_GENERATOR_SIZE 17L
/*
 * Class:     electrosphere_client_fluid_cache_FluidChunkData
 * Method:    allocate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_electrosphere_client_fluid_cache_FluidChunkData_allocate
  (JNIEnv *, jobject);

/*
 * Class:     electrosphere_client_fluid_cache_FluidChunkData
 * Method:    free
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_electrosphere_client_fluid_cache_FluidChunkData_free
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
