package electrosphere.server.physics.terrain.generation.interfaces;

import org.graalvm.polyglot.HostAccess.Export;

/**
 * A voxel generated by a chunk generator
 */
public class GeneratedVoxel {
    
    /**
     * The type of the voxel
     */
    @Export
    public int type;

    /**
     * The weight of the voxel
     */
    @Export
    public float weight;

}
